name: Trigger

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Update LAST_UPDATED.txt
      run: |
        date '+%Y-%m-%d %H:%M:%S %Z' > LAST_UPDATED.txt
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add LAST_UPDATED.txt
        git commit -m "Update LAST_UPDATED.txt [skip ci]" || echo "No changes to commit"
    - name: Push changes
      run: |
        git push
